#!/bin/bash

# getopts
while getopts "t:c:" opt; do
    case $opt in
    t) APP=$OPTARG ;;
    c) WS=$OPTARG ;;
    *) echo "No reasonable options found" ;;
    esac
done

# handle workspace
TILE_WS=$(i3-msg -t get_workspaces | jq | grep name | grep $WS)
if [[ "$?" -eq 0 ]]; then
    i3-msg workspace $WS
fi

# handle application
TILE_APP=$(xdotool search $APP)
if [[ "$?" -eq 0 ]]; then
    i3-msg workspace $WS
else
    i3-msg workspace $WS
    i3-msg exec $APP
fi
